### ISSUE TITLE
Export values of generated matrices

### ISSUE THREAD

**Issue by muelli1975** [tschw/angler.js#1]
Hello,

you have created a very interesting app for generating anaglyphs! Is it somehow possible to export the 3x3 transformation matrices to use them in cosima or spm? It was possible to have a look at the output of the script with the developer tools in chrome, and I entered the values into cosima_anamatrix.exe. It looked okay, but the gamma was not correct. A great feature would be the possibility to save anaglyph-matrixes for cosima, which are simple text files or to just export the linear matrix.

Best regards and thank you for your interesting approach on creating angalyphs,
Christoph

**Comment by tschw** [comment]
Hi,

actually the app is a demo for the library.

When enabled, gamma correction to [sRGB](https://en.wikipedia.org/wiki/SRGB) is performed [here](https://github.com/tschw/angler.js/blob/43d9c408d0e61727165388e8eed7c947ca7971d8/app/classes/AnaglyphVideoPlayer.js#L119-L127). If it's turned off (that is, `Ignore Display Nonlinearity` is clicked in the app), it should create matrices for plain RGB, but that might not work that well, because the physical model is based on light energy rather than some kind of (somewhat _lineraly percieved_) intensity values that correspond to voltage levels that go into a display device and are in fact nonlinear. A matrix can only do linear transformation while gamma correction is not.

If gamma correction is enabled, it will generate matrices for linear RGB, if disabled it will create matrices for distorted display RGB.
